# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiBo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod ‘AFNetworking’
pod ’SDWebImage’
pod ’SVProgressHUD’

  # Pods for WeiBo

end
